OPENROUTER_API_KEY=your_openrouter_api_key_here
OPENROUTER_CONCURRENCY=32
# Cost control (recommended for large runs):
OPENROUTER_FREE_ONLY=true
OPENROUTER_AI_WORDS_MIN=10
OPENROUTER_AI_WORDS_MAX=150
# OPENROUTER_MAX_PROMPT_PRICE=0.0000005
# OPENROUTER_MAX_COMPLETION_PRICE=0.000001
# OPENROUTER_MODELS=deepseek/deepseek-v4-flash:free,google/gemma-4-26b-a4b-it:free
MINIPILE_DATA_DIR=dataset/minipile/data
MINIPILE_OUTPUT_DIR=output
MINIPILE_SPLITS=train,validation,test
MINIPILE_FROM=0
MINIPILE_TO=1000
MINIPILE_CHUNK_SIZE=1000
GENERATION_MODE=sandwitch # append or sandwitch
